data_configs:
  lang_pair: "zh-en"
  train_data:
    - "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/train/zh.small.txt"
    - "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/train/en.small.txt"
  valid_data:
    - "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/test/mt03.small.src"
    - "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/test/mt03.small.ref0"
  bleu_valid_reference: "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/test/mt03.small.ref"
  vocabularies:
    - type: "word"
      dict_path: "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/vocab/zh.json"
      max_n_words: 30000
    - type: "word"
      dict_path: "/home/perceptron/workspace/nlp/data/NIST-ZH-EN/vocab/en.json"
      max_n_words: 30000
  max_len:
    - 80
    - 80
  num_refs: 4
  eval_at_char_level: false

model_configs:
  model: Transformer
  n_layers: 6
  n_head: 8
  d_word_vec: 512
  d_model: 512
  d_inner_hid: 2048
  dropout: 0.1
  proj_share_weight: true
  label_smoothing: 0.1

optimizer_configs:
  optimizer: "adam"
  learning_rate: 0.2
  grad_clip: -1.0
  optimizer_params: ~
  schedule_method: noam
  scheduler_configs:
    d_model: 512
    warmup_steps: 8000

training_configs:
  seed: 1234
  max_epochs: 5
  shuffle: true
  use_bucket: true
  batch_size: 1024
  batching_key: "tokens"
  update_cycle: 4
  valid_batch_size: 20
  disp_freq: 1
  save_freq: 1
  num_kept_checkpoints: 1
  loss_valid_freq: 1
  bleu_valid_freq: 1
  bleu_valid_batch_size: 5
  bleu_valid_warmup: 1
  bleu_valid_configs:
    max_steps: 150
    beam_size: 5
    alpha: 0.0
    sacrebleu_args: "--tokenize none -lc"
    postprocess: false
  early_stop_patience: 50